#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install-y  nginx
sudo ufw allow 'Nginx HTTP'

echo -e "Hello World" > /var/www/html/index.html
sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;\n}\n' /etc/nginx/sites-available/default 
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sed -i '46i error_page 404 /error404.html;\n' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
