#!/usr/bin/env bash

sudo pt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "48i $redirect" /etc/nginx/sites-available/default
new404="\\\terror_page 404 /404.html;"
sudo sed -i "49i $new404" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
